# Generated by Django 3.2.4 on 2021-06-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=255)),
                ('combined', models.FloatField()),
                ('emission', models.FloatField(default=0)),
                ('carbon_rating', models.FloatField()),
                ('smog_rating', models.FloatField()),
            ],
        ),
    ]
