# Generated by Django 3.2.4 on 2021-06-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='thumbnail',
            field=models.URLField(default='https://www.solidbackgrounds.com/images/950x350/950x350-vermilion-cinnabar-solid-color-background.jpg'),
        ),
    ]
