# Generated by Django 3.2.4 on 2021-06-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crossover',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hatchbackorsedan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='minivanorsuv',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pickuptruck',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sportscar',
            name='name',
        ),
    ]
