# Generated by Django 3.2.4 on 2021-06-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210626_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossover',
            name='emission',
            field=models.FloatField(default='somestring'),
        ),
    ]
