# Generated by Django 3.2.4 on 2021-06-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_automobile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='thumbnail',
            field=models.CharField(default='https://www.solidbackgrounds.com/images/950x350/950x350-vermilion-cinnabar-solid-color-background.jpg', max_length=255),
        ),
    ]
