# Generated by Django 3.2.4 on 2021-06-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_crossover_emission'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupe',
            name='emission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hatchbackorsedan',
            name='emission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='minivanorsuv',
            name='emission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pickuptruck',
            name='emission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sportscar',
            name='emission',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='crossover',
            name='emission',
            field=models.FloatField(default=0),
        ),
    ]
