# Generated by Django 3.2.4 on 2021-06-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210626_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupe',
            name='emission',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crossover',
            name='emission',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hatchbackorsedan',
            name='emission',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='minivanorsuv',
            name='emission',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pickuptruck',
            name='emission',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sportscar',
            name='emission',
            field=models.FloatField(),
        ),
    ]
