# Generated by Django 3.2.4 on 2021-06-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210626_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupe',
        ),
        migrations.DeleteModel(
            name='Crossover',
        ),
        migrations.DeleteModel(
            name='HatchbackOrSedan',
        ),
        migrations.DeleteModel(
            name='MinivanOrSUV',
        ),
        migrations.DeleteModel(
            name='PickupTruck',
        ),
        migrations.DeleteModel(
            name='SportsCar',
        ),
    ]
